spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bitbucket_bot
    username: postgres
    driver-class-name: org.postgresql.Driver
    password:
  liquibase:
    change-log: classpath:liquibase/change-log.xml
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
bitbucketbot:
  server-send:
    url: http://188.225.35.149:8080/api/send
  bitbucket:
    token: Nzg5NjUyNDQwMzk2OlA+6naQz02+GxOG0Q9li/jnsn7E
    url-pull-request-open: http://localhost:7990/rest/api/1.0/dashboard/pull-requests?limit=150&state=OPEN
    url-pull-request-close: http://localhost:7990/rest/api/1.0/dashboard/pull-requests?limit=150&closedSince=86400
    url-pull-request-comment: http://localhost:7990/rest/api/1.0/projects/{projectKey}/repos/{repositorySlug}/pull-requests/{pullRequestId}/comments/{commentId}
server:
  port: 8018
