spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bitbucket_bot
    username: postgres
    driver-class-name: org.postgresql.Driver
    password:
  liquibase:
    change-log: classpath:liquibase/change-log.xml
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
bitbucketbot:
  telegram:
    bot-username: bitbucket_sadtech_bot
    bot-token: 1096235968:AAHvIy_mlZJXiNc9aDQWtCuiksz9YGknoXE
    proxy-config:
      host: 212.237.23.75
      port: 1080
      type: SOCKS5
      user: upagge
      password: seAbotd9Bidu%ZqZB3g4
  bitbucket:
    token: Nzg5NjUyNDQwMzk2OlA+6naQz02+GxOG0Q9li/jnsn7E
    url-pull-request-open: http://192.168.236.164:7990/rest/api/1.0/dashboard/pull-requests?limit=150&state=OPEN
    url-pull-request-close: http://192.168.236.164:7990/rest/api/1.0/dashboard/pull-requests?limit=150&closedSince=86400
